Shop/Models/Weather/AccuWeatherSearchViewModel.cs
namespace Shop.Models.Weather
{
    public class AccuWeatherSearchViewModel
    {
        public string? CityName { get; set; } = string.Empty;

    }
}

Shop/Models/Weather/AccuWeatherViewModel.cs
namespace Shop.Models.Weather
{
    public class AccuWeatherViewModel
    {
        public string CityName { get; set; } = string.Empty;
        public string EffectiveDate { get; set; } = string.Empty;
        public Int64 EffectiveEpochDate { get; set; }
        public int Severity { get; set; }
        public string Text { get; set; } = string.Empty;
        public string Category { get; set; } = string.Empty;
        public string EndDate { get; set; } = string.Empty;
        public Int64 EndEpochDate { get; set; }


        public string DailyForecastsDate { get; set; } = string.Empty;
        public int DailyForecastsEpochDate { get; set; }

        public double TempMinValue { get; set; }
        public string TempMinUnit { get; set; } = string.Empty;
        public int TempMinUnitType { get; set; }

        public double TempMaxValue { get; set; }
        public string TempMaxUnit { get; set; } = string.Empty;
        public int TempMaxUnitType { get; set; }

        public int DayIcon { get; set; }
        public string DayIconPhrase { get; set; } = string.Empty;
        public bool DayHasPrecipitation { get; set; }
        public string DayPrecipitationType { get; set; } = string.Empty;
        public string DayPrecipitationIntensity { get; set; } = string.Empty;

        public int NightIcon { get; set; }
        public string NightIconPhrase { get; set; } = string.Empty;
        public bool NightHasPrecipitation { get; set; }
        public string NightPrecipitationType { get; set; } = string.Empty;
        public string NightPrecipitationIntensity { get; set; } = string.Empty;

        public string MobileLink { get; set; } = string.Empty;
        public string Link { get; set; } = string.Empty;
    }
}

Shop/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.ApplicationServices.Services;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.Models.Weather;

namespace Shop.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IWeatherForecastServices _WeatherForecastServices;

        private readonly IWeatherForecastServices _weather;
        public WeatherController
        (IWeatherForecastServices weatherForecastServices)
        {
            _weather = weatherForecastServices;
            _WeatherForecastServices = weatherForecastServices;
        }
        public IActionResult Index()
        {
            return View();
        }

        //teha action SearchCity
        [HttpPost]
        public async Task<IActionResult> SearchCity(AccuWeatherSearchViewModel model)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("city", "weather", new { city = model.CityName });
            }
            return View(model);

            //var result = await _WeatherForecastServices.AccuWeatherResult(dto);
            //return View("Index", result);
        }
        [HttpGet]
        public IActionResult City(string city)
        {
            AccuLocationWeatherResultDto dto = new();
            dto.CityName = city;

            //_weatherForecastServices.AccuWeatherResult(dto);
            _WeatherForecastServices.AccuWeatherResultWebClient(dto);
            AccuWeatherViewModel vm = new();
            vm.CityName = dto.CityName;
            vm.EffectiveDate = dto.EffectiveDate;
            vm.EffectiveEpochDate = dto.EffectiveEpochDate;
            vm.Severity = dto.Severity;
            vm.Text = dto.Text;
            vm.Category = dto.Category;
            vm.EndDate = dto.EndDate;
            vm.EndEpochDate = dto.EndEpochDate;
            vm.DailyForecastsDate = dto.DailyForecastsDate;
            vm.DailyForecastsEpochDate = dto.DailyForecastsEpochDate;

            vm.TempMinValue = dto.TempMinValue;
            vm.TempMinUnit = dto.TempMinUnit;
            vm.TempMinUnitType = dto.TempMinUnitType;

            vm.TempMaxValue = dto.TempMaxValue;
            vm.TempMaxUnit = dto.TempMaxUnit;
            vm.TempMaxUnitType = dto.TempMaxUnitType;

            vm.DayIcon = dto.DayIcon;
            vm.DayIconPhrase = dto.DayIconPhrase;
            vm.DayHasPrecipitation = dto.DayHasPrecipitation;
            vm.DayPrecipitationType = dto.DayPrecipitationType;
            vm.DayPrecipitationIntensity = dto.DayPrecipitationIntensity;

            vm.NightIcon = dto.NightIcon;
            vm.NightIconPhrase = dto.NightIconPhrase;
            vm.NightHasPrecipitation = dto.NightHasPrecipitation;
            vm.NightPrecipitationType = dto.NightPrecipitationType;
            vm.NightPrecipitationIntensity = dto.NightPrecipitationIntensity;

            vm.MobileLink = dto.MobileLink;
            vm.Link = dto.Link;

            return View(vm);
        }
    }
}

Shop/Views/Weather/City.cshtml
@model Shop.Models.Weather.AccuWeatherViewModel

<div class="container">
    <h2>Forecast for the selected city</h2>
    <h2>@Html.DisplayFor(model => model.CityName)</h2>
    <hr />
    <dl class="row text-dark">
        <div>
            <dt class="col-sm-2">
                Temperature Min (Celsius):
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TempMinValue) °C
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Temperature Max (Celsius):
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TempMaxValue) °C
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Severity:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Severity)
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Category:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category)
            </dd>
        </div>
        <div>
            <dt class="col-sm-2">
                Weather Text:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Text)
            </dd>
        </div>
    </dl>
</div>

Shop/Views/Weather/Index.cshtml
@model Shop.Models.Weather.AccuWeatherSearchViewModel

<h1>Search City</h1>

<div class="container">
    <form method="post">
        <div class="container">
            <div class="form-group col-md-offset-3 col-md-5">
                <h2>Searh the forecast in a city</h2>
                <label asp-for="CityName" style="font-family: Arial"></label>
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>
        </div>
        <div class="container">
            <div class="form-group col-md-offset-3 col-md-5" style="margin-top:10px">
                <button asp-controller="Weather" asp-action="searchCity" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>