Shop/Models/RealEstate/RealEstateCreateUpdateViewModel.cs
using Shop.Core.Dto;

namespace Shop.Models.RealEstate
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public List<IFormFile> Files { get; set; }
        public List<RealEstateImagesViewModel> Image { get; set; }
            = new List<RealEstateImagesViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

    }
}

Shop/Models/RealEstate/RealEstateDeleteViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public List<RealEstateImagesViewModel> Image { get; set; }
            = new List<RealEstateImagesViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateDetailsViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public List<RealEstateImagesViewModel> Image { get; set; }
            = new List<RealEstateImagesViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateImagesViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateImagesViewModel
    {
        public Guid Id { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateIndexViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateIndexViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/Spaceships/ImagesViewModel.cs
namespace Shop.Models.Spaceships
{
    public class ImagesViewModel
    {
        public Guid ImageId { get; set; }
        public string? FilePath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

Shop/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.ApplicationServices.Services;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.Data;
using Shop.Models.RealEstate;
using Shop.Models.Spaceships;
using System.Collections.Generic;

namespace Shop.Controllers
{
    public class RealEstateController : Controller
    {
        private readonly ShopContext _context;
        private readonly IRealEstateService _realEstateService;
        private readonly IFileServices _fileServices;
        public RealEstateController
            (
                ShopContext context,
                IRealEstateService realEstateService,
                IFileServices fileServices
            )
        {
            _context = context;
            _realEstateService = realEstateService;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.RealEstate
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Area = x.Area,
                    Location = x.Location,
                    RoomNumber = x.RoomNumber,
                    BuildingType = x.BuildingType
                });

            return View(result);
        }

        
        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel result = new();
            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Area = vm.Area,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.Id,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId
                    }).ToArray()
            };
            var result = await _realEstateService.Create(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstateService.DetailAsync(id);
            if (realEstate == null)
            {
                return NotFound();
            }
            var images = await ImageMethod(id);

            var vm = new RealEstateDeleteViewModel();
            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstate = await _realEstateService.Delete(id);

            if (realEstate == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstateService.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }
            var images = await ImageMethod(id);

            var vm = new RealEstateCreateUpdateViewModel();
            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Area = vm.Area,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.Id,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId
                    }).ToArray()
            };
            var result = await _realEstateService.Update(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var RealEstate = await _realEstateService.DetailAsync(id);
            if (RealEstate == null)
            {
                return NotFound();
            }
   
            var images = await ImageMethod(id);

            var vm = new RealEstateDetailsViewModel();
            vm.Id = RealEstate.Id;
            vm.Area = RealEstate.Area;
            vm.Location = RealEstate.Location;
            vm.RoomNumber = RealEstate.RoomNumber;
            vm.BuildingType = RealEstate.BuildingType;
            vm.CreatedAt = RealEstate.CreatedAt;
            vm.ModifiedAt = RealEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        //[HttpPost]
        //public async Task<IActionResult> RemoveImage(RealEstateImagesViewModel vm)
        //{
        //    var dto = new FileToDatabaseDto()
        //    {
        //        Id = vm.Id
        //    };
        //    var image = await _fileServices.RemoveImageFromApi(dto);
        //    if (image == null)
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }

        //    return RedirectToAction(nameof(Index));
        //}


        public async Task<RealEstateImagesViewModel[]> ImageMethod(Guid id)
        {
            // Проверяем, есть ли вообще данные
            var images = await _context.FileToDatabase
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImagesViewModel
                {
                    RealEstateId = y.RealEstateId,
                    Id = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    // Преобразуем бинарные данные в base64 для отображения в <img>
                    Image = "data:image/gif;base64," + Convert.ToBase64String(y.ImageData)
                })
                .ToArrayAsync();

            // Возвращаем результат
            return images;
        }
    }
}

Shop/Views/RealEstate/CreateUpdate.cshtml
@model Shop.Models.RealEstate.RealEstateCreateUpdateViewModel

@if (Model.Id.HasValue)
{
	<h1>Update</h1>
}
else
{
	<h1>Create</h1>
}

<div>
	<h1>Create</h1>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="Id" type="hidden" />
		<input asp-for="CreatedAt" type="hidden" />
		<input asp-for="ModifiedAt" type="hidden" />

		<div class="form-group row">
			<label asp-for="Area" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Area" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Location" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Location" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="RoomNumber" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="BuildingType" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Files" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<div class="custom-file">
					<input asp-for="Files" class="form-control" multiple type="file" />
				</div>
			</div>
		</div>
		@foreach (var images in Model.Image)
		{
			<partial name="_Images" model="images" />
			<input asp-action="RemoveImage" asp-controller="RealEstate" asp-route-imageId="@images.Id" type="submit" class="btn btn-danger" value="Remove Image" />
		}
		@if (Model.Id.HasValue)
		{
			<input asp-action="update" asp-controller="RealEstate" type="submit" class="btn btn-primary" value="Update" />
		}
		else
		{
			<input asp-action="create" asp-controller="RealEstate" type="submit" class="btn btn-primary" value="Create" />
		}
		<a asp-action="Index" asp-controller="RealEstate" class="btn btn-success">Back</a>
	</form>
</div>

Shop/Views/RealEstate/Delete.cshtml
@model Shop.Models.RealEstate.RealEstateDeleteViewModel

<h1>Delete</h1>
<div>
	<h4>RealEstate</h4>
	<hr />
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Id" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Id)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="Area" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Area)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="Location" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Location)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.RoomNumber)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.BuildingType)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.CreatedAt)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.ModifiedAt)
		</div>
	</dl>
	@foreach (var images in Model.Image)
	{
		<partial name="_Images" model="images" />
	}
	
	<form asp-action="DeleteConfirmation">
		<input type="hidden" asp-for="Id"/>
		<input type="submit" value="Delete" class="btn btn-danger"/>
		<a asp-action="Index" asp-controller="RealEstate" class="btn btn-primary">Back</a>
	</form>
	
	
</div>

Shop/Views/RealEstate/Details.cshtml
@model Shop.Models.RealEstate.RealEstateDetailsViewModel

<h1>Details</h1>
<div>
	<h4>RealEstate</h4>
	<hr />
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Id" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Id)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="Area" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Area)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="Location" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Location)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.RoomNumber)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.BuildingType)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.CreatedAt)
		</div>
	</dl>

	<dl class="row">
		<div class="form-group row">
			<label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.ModifiedAt)
		</div>
	</dl>
	@if (Model.Image != null && Model.Image.Any())
	{
		<div>
			@foreach (var image in Model.Image)
			{
				<div style="margin-bottom: 15px;">
					<img src="@image.Image" alt="@image.ImageTitle" style="max-width: 300px;" />
					<p>@image.ImageTitle</p>
				</div>
			}
		</div>
	}
	else
	{
		<p>No photos available.</p>
	}
	
	<a asp-action="Index" asp-controller="RealEstate" class="btn btn-primary">Back</a>
	
</div>

Shop/Views/RealEstate/Index.cshtml
@model IEnumerable<Shop.Models.RealEstate.RealEstateIndexViewModel>
@{
	int nr = 1;
}
@{
	string mark = "*";
}
<div>
	<a asp-action="create" asp-controller="RealEstate" type="submit" class="btn btn-primary"> Create </a>
</div>
<div class="h1">
	RealEstate
</div>
<form method="post">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col"> Id </th>
				<th scope="col"> Area </th>
				<th scope="col"> Location </th>
				<th scope="col"> RoomNumber </th>
				<th scope="col"> BuildingType </th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>

			@foreach (var RealEstates in Model)
			{
				<tr>
					<td>
						@nr @mark

					</td>
					<td>
						@RealEstates.Area
					</td>
					<td>
						@RealEstates.Location
					</td>
					<td>
						@RealEstates.RoomNumber
					</td>
					<td>
						@RealEstates.BuildingType
					</td>
					<td>
						<a asp-action="details" asp-controller="RealEstate" asp-route-id="@RealEstates.Id" class="btn btn-outline-primary"> Details </a>
						<a asp-action="update" asp-controller="RealEstate" asp-route-id="@RealEstates.Id" class="btn btn-outline-warning"> Update </a>
						<a asp-action="delete" asp-controller="RealEstate" asp-route-id="@RealEstates.Id" class="btn btn-outline-danger"> Delete </a>
					</td>
				</tr>
				nr++;
				mark += "*";
			}
		</tbody>
	</table>
</form>

Shop/Views/RealEstate/_Images.cshtml
@model Shop.Models.RealEstate.RealEstateImagesViewModel


<div class="form-group row col-sm-4 offset-2">
	<div>@Model.ImageTitle</div>
	<img class="card-image-top" src="@Model.Image" asp-append-version="true"/>
</div>